project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Kumeyaay Ethnobotany"
  page-navigation: true
  site-url: "https://shannonrankin.github.io/ethnobotany"
  repo-url: "https://github.com/shannonrankin/ethnobotany"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"

  sidebar:
    background: "#D9E3E4"
    logo: "https://www.cuyamaca.edu/_resources/assets/images/faculty-staff-resources/CC-LogoPrimary-1colorRGB.jpg"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    tools:
      - icon: globe
        href: https://shannonrankin.github.io/ethnobotany
        text: "Ethnobotany Projects"
      - icon: github
        href: https://github.com/shannonrankin/ethnobotany
        text: "Ethnobotany Projects"
    contents:
      - href: index.qmd
        text: Home
      - href: content/utility_dashboard.qmd
        text: "Utility Life Cycle"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

resources:
  - data/
  - content/images/
